/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Spisok;

import java.util.ArrayList;

public class Main {
   public static void main(String[] args) {
      // создание списка
      ArrayList<String> list = new ArrayList<String>();

      // добавление элементов в список
      list.add("Первый элемент");
      list.add("Второй элемент");
      list.add("Третий элемент");

      // вывод списка на экран
      for (String elem : list) {
         System.out.println(elem);
      }
   }
}